---
- hosts: monitor
  become: true
  vars:
    details:
      - program: jenkins_publish
        main: jenkins_publish.py
      - program: board_config
        main: board_config.py
      - program: blinkt_display
        main: blinkt_display.py
      - program: control
        main: control.py
      - program: jenkins_deploy
        main: jenkins_deploy.py
    programs: "{{details | json_query('[*].program')}}"

  tasks:
    - name: Create program directories
      file:
        dest: "/opt/monitor/apps/{{item}}/logs"
        state: directory
        mode: 01777
        owner: nobody
      with_items: "{{programs}}"
        
    - name: Copy program files
      copy:
        src: "files/programs/{{item[0].program}}/{{item[1]}}"
        dest: "/opt/monitor/apps/{{item[0].program}}"
        owner: nobody
        force: no
      with_nested:
        - "{{details}}"
        - - program
          - config

    - name: Create venv from requirements
      pip:
        requirements: "/opt/monitor/apps/{{item}}/program/requirements.txt"
        virtualenv: "/opt/monitor/apps/{{item}}/venv"
        virtualenv_command: "/usr/bin/python3 -m venv"
      with_items: "{{programs}}"

    - name: Create systemd config file
      template:
        dest: /etc/systemd/system/{{item.program}}.service
        src: files/service.template
      with_items: "{{details}}"

    - name: Configure systemd
      systemd:
        name: "{{item}}"
        daemon_reload: true
        enabled: true
        state: started
      with_items: "{{programs}}"
    
...
