---
- name: Get virtual env binaries
  package:
    name: "{{package}}"
  with_items:
    - python3
    - python3-venv
    - python3-dev
    - python3-pip
    - python3-setuptools
  loop_control:
    loop_var: package
...
