---
url: 'https://jenkins.hostname/job/'
auth:
  user: user.name
  token: user.token
mq: localhost
pause: 10 # seconds between polling jenkins
jobs:
  - job: path/to/jenkins/job1
    topic: jenkins/job/topic1
  - job: path/to/jenkins/job2
    topic: jenkins/job/topic2
...
