---
jobs: # topics to subscribe
  - jenkins/job/build/release
  - 
  - 
  - 
  - 
  - 
  -
  -
colours: #  topic.result : [r, g, b]
  SUCCESS: [10, 200, 20]
  FAILURE: [255, 0, 0]
  UNSTABLE: [255, 204, 0]
  ABORTED: [82, 82, 82]
...


